# Generated by Django 5.2.5 on 2025-08-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario', 'Usuario')], default='Usuario', max_length=32),
        ),
    ]
