# Generated by Django 5.2.3 on 2025-08-27 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario')], default='user', max_length=32),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Ubicación')),
                ('external_id', models.CharField(blank=True, max_length=50, verbose_name='ID')),
                ('manager_name', models.CharField(blank=True, max_length=120, verbose_name='Encargado')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
