# Generated by Django 5.2.3 on 2025-08-27 01:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'ene'), (2, 'feb'), (3, 'mar'), (4, 'abr'), (5, 'may'), (6, 'jun'), (7, 'jul'), (8, 'ago'), (9, 'sep'), (10, 'oct'), (11, 'nov'), (12, 'dic')])),
                ('m3_water', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('m3_gas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fixed_charge', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), help_text='Cargo fijo del mes (CLP)', max_digits=10)),
                ('price_per_m3', models.DecimalField(decimal_places=4, default=Decimal('950.0000'), help_text='Precio unitario por m³ ese mes (CLP)', max_digits=10)),
                ('iva_rate', models.DecimalField(decimal_places=2, default=Decimal('0.19'), help_text='IVA (por ejemplo 0.19)', max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_consumptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', '-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
