# Generated by Django 5.2.3 on 2025-08-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_gasconsumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasconsumption',
            name='month',
            field=models.CharField(max_length=10),
        ),
    ]
