# Generated by Django 5.2.3 on 2025-08-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_gasconsumption_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasconsumption',
            options={'ordering': ['year', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='gasconsumption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gasconsumption',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gasconsumption',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='gasconsumption',
            name='fixed_charge',
        ),
        migrations.RemoveField(
            model_name='gasconsumption',
            name='iva_rate',
        ),
        migrations.RemoveField(
            model_name='gasconsumption',
            name='price_per_m3',
        ),
    ]
