# Generated by Django 5.2.3 on 2025-08-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_gasconsumption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Última mantención'),
        ),
        migrations.AddField(
            model_name='profile',
            name='maintenance_interval_months',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Intervalo mantención (meses)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima mantención'),
        ),
    ]
