# Generated by Django 5.2.3 on 2025-08-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_last_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='report_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email para reportes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], default='pdf', max_length=4, verbose_name='Formato de reporte'),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_frequency',
            field=models.CharField(choices=[('off', 'Nunca'), ('m', 'Mensual'), ('q', 'Trimestral')], default='off', max_length=10, verbose_name='Frecuencia de reporte'),
        ),
    ]
