# Generated by Django 5.2.17 on 2026-08-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_deduplicar_consumo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasconsumption',
            options={'ordering': ['-year', 'id'], 'verbose_name': 'Consumo', 'verbose_name_plural': 'Consumos'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='gasconsumption',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='gasconsumption',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='gasconsumption',
            name='m3_gas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='M³ gas'),
        ),
        migrations.AlterField(
            model_name='gasconsumption',
            name='m3_water',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='M³ agua'),
        ),
        migrations.AlterField(
            model_name='gasconsumption',
            name='month',
            field=models.CharField(choices=[('ene', 'Enero'), ('feb', 'Febrero'), ('mar', 'Marzo'), ('abr', 'Abril'), ('may', 'Mayo'), ('jun', 'Junio'), ('jul', 'Julio'), ('ago', 'Agosto'), ('sep', 'Septiembre'), ('oct', 'Octubre'), ('nov', 'Noviembre'), ('dic', 'Diciembre')], max_length=10, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='gasconsumption',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link del equipo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario')], default='user', max_length=32, verbose_name='Rol'),
        ),
        migrations.AddIndex(
            model_name='gasconsumption',
            index=models.Index(fields=['user', 'year'], name='consumo_usuario_anio_idx'),
        ),
        migrations.AddConstraint(
            model_name='gasconsumption',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'month'), name='consumo_unico_por_usuario_y_mes'),
        ),
    ]
