# Generated by Django 5.2.5 on 2025-08-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='fecha')),
                ('boiler', models.CharField(db_column='caldera', max_length=100)),
                ('water_m3', models.DecimalField(db_column='agua_m3', decimal_places=2, max_digits=12)),
                ('gas_m3', models.DecimalField(db_column='gas_m3', decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'consumos_calderas',
            },
        ),
    ]
